kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: suse-ai-kubeflow-demo
  namespace: fleet-local
spec:
  repo: https://github.com/guangyee/manifests
  branch: main
  targetNamespace: suse-private-ai
  paths:
  - ./example
  forceSyncGeneration: 1
