apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# List of resources to manage. Can include local files and remote URLs.
resources:
  # Example of a remote raw GitHub URL for a specific YAML file.
  - https://github.com/kubeflow/manifests.git/example?version=v1.11.0
